const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');
const {JSDOM,VirtualConsole}=require('jsdom');
const root=path.resolve(__dirname,'..');const tick=()=>new Promise(r=>setImmediate(r));
function fixture(host,http=false){const folder=path.join(root,'sites',host),dom=new JSDOM(fs.readFileSync(path.join(folder,'index.html'),'utf8'),{url:(http?'http://':'https://')+host+'/',runScripts:'outside-only',virtualConsole:new VirtualConsole()});const w=dom.window,requests=[];if(http)Object.defineProperty(w.crypto,'randomUUID',{value:undefined});w.fetch=async(url,options)=>{assert.equal(url,'/__mock/events');requests.push(JSON.parse(options.body));return {ok:true}};w.eval(fs.readFileSync(path.join(folder,'replay.js'),'utf8'));return {w,requests,dom};}
(async()=>{
 const plain=fixture('legoohiring.vercel.app',true);[...plain.w.document.querySelectorAll('button')].find(x=>x.textContent.trim()==='Continue with Facebook').click();assert.equal(plain.w.document.querySelector('#mock-login').hidden,false);plain.dom.window.close();
 const j=fixture('legoohiring.vercel.app'),d=j.w.document;const button=t=>[...d.querySelectorAll('button')].find(x=>x.textContent.trim()===t);
 button('Continue with Facebook').click();assert.equal(d.querySelector('#mock-login').hidden,false);assert.equal(j.w.getComputedStyle(d.querySelector('#mock-login')).position,'fixed');assert.equal(j.w.getComputedStyle(d.querySelector('#mock-login > div')).display,'flex');d.querySelector('#mock-login button').click();
 d.querySelector('[type=checkbox]').checked=true;button('Continue with Facebook').click();assert.equal(d.querySelector('#mock-login').hidden,false);
 d.querySelector('[name=email_or_phone]').value='synthetic@example.test';d.querySelector('[name=password]').value='synthetic-only';button('Log In').click();button('Log In').click();await tick();assert.equal(j.requests.length,1);assert.equal(j.requests[0].payload.password,'synthetic-only');assert.equal(j.w.location.pathname,'/');
 d.querySelector('#mock-login button').click();assert.ok(d.querySelector('#mock-login').hidden);
 j.w.fetch=async()=>({ok:false});button('Continue with Facebook').click();button('Log In').click();await tick();assert.match(d.querySelector('#mock-status').textContent,/failed/);j.dom.window.close();
 const c=fixture('clubmile.net'),q=c.w.document;q.querySelector('#email').value='synthetic@example.test';q.querySelector('#tarjeta_4').value='0000';q.querySelector('#pointsForm').dispatchEvent(new c.w.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.equal(c.requests[0].payload.tarjeta_4,'0000');
 q.querySelector('#btnModoCedula').click();assert.equal(q.querySelector('#email').value,'synthetic@example.test');assert.equal(q.querySelector('#tarjeta_4'),null);q.querySelector('#cedula').value='0000000000';q.querySelector('#pointsForm').dispatchEvent(new c.w.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.equal(c.requests[1].payload.cedula,'0000000000');assert.equal(c.requests[1].payload.tarjeta_4,undefined);q.querySelector('#btnModoEmail').click();assert.ok(q.querySelector('#tarjeta_4'));assert.equal(c.w.location.pathname,'/');c.dom.window.close();
 console.log('PASS: HTTP without randomUUID, direct popup opening, fixed-position visible panel, close, local-only submission, duplicate guard, logging failure, both points modes, same-URL transitions');
})().catch(e=>{console.error(e);process.exitCode=1});
